#entryScript: echo_score.py
entryScript: 5echo_score.py
runtime: python
#condaFile: scoring-env.yml
condaFile: 5conda_env_v_1_0_0.yml
extraDockerfileSteps:
schemaFile:
sourceDirectory:
enableGpu: False
baseImage:
baseImageRegistry: